POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
  "username": "vietanh",
  "password": "2011"
}

###

POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "username": "vietanh",
  "password": "2011"
}

###

POST http://localhost:8000/api/product/new
Content-Type: application/json

{
  "name": "do choi 3",
  "description": "do choi 3 ne",
  "price": 150,
  "imageURL": "..."
}

###
GET http://localhost:8000/api/product/GetAllProducts

###
GET  http://localhost:8000/api/product/6648bbc2b647ba693d8c882e